name: Run Tests and Mutation Testing

on:
    push:
    pull_request:

jobs:
    test-and-mutate-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 23
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '23'

            - name: Run unit tests
              run: mvn test

            - name: Run PIT mutation testing
              run: mvn org.pitest:pitest-maven:mutationCoverage
